config/routes.rb
Rails.application.routes.draw do
  resources :products
  get 'base_template/index'
  get 'settings/index'
  get 'settings/custom_account'
  get 'settings/change_password'
  get 'settings/index'
  get 'settings/custom_account'
  get 'stocks/analysis'
  get 'sales/analysis'
  resources :stocks
  resources :producteds
  resources :sales
  resources :companies
  resources :settings
  get 'home/index'
  get 'home/index'
  devise_for :users
  root 'home#index'
end

app/models/producted.rb
class Producted < ActiveRecord::Base
end

app/controllers/producteds_controller.rb
class ProductedsController < ApplicationController
  before_action :set_producted, only: [:show, :edit, :update, :destroy]

  # GET /producteds
  # GET /producteds.json
  def index
    @producteds = Producted.all
  end

  # GET /producteds/1
  # GET /producteds/1.json
  def show
  end

  # GET /producteds/new
  def new
    @producted = Producted.new
  end

  # GET /producteds/1/edit
  def edit
  end

  # POST /producteds
  # POST /producteds.json
  def create
    @producted = Producted.new(producted_params)

    respond_to do |format|
      if @producted.save
        format.html { redirect_to @producted, notice: 'Producted was successfully created.' }
        format.json { render :show, status: :created, location: @producted }
      else
        format.html { render :new }
        format.json { render json: @producted.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /producteds/1
  # PATCH/PUT /producteds/1.json
  def update
    respond_to do |format|
      if @producted.update(producted_params)
        format.html { redirect_to @producted, notice: 'Producted was successfully updated.' }
        format.json { render :show, status: :ok, location: @producted }
      else
        format.html { render :edit }
        format.json { render json: @producted.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /producteds/1
  # DELETE /producteds/1.json
  def destroy
    @producted.destroy
    respond_to do |format|
      format.html { redirect_to producteds_url, notice: 'Producted was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producted
      @producted = Producted.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def producted_params
      params.require(:producted).permit(:name, :price, :type, :amount, :validity, :category, :created, :modificated)
    end
end

app/helpers/producteds_helper.rb
module ProductedsHelper
end

app/views/producteds/_form.html.erb
<%= form_for(@producted) do |f| %>
  <% if @producted.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@producted.errors.count, "error") %> prohibited this producted from being saved:</h2>

      <ul>
      <% @producted.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :validity %><br>
    <%= f.date_select :validity %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.number_field :category %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/producteds/edit.html.erb
<h1>Editing Producted</h1>

<%= render 'form' %>

<%= link_to 'Show', @producted %> |
<%= link_to 'Back', producteds_path %>

app/views/producteds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Producteds</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Type</th>
      <th>Amount</th>
      <th>Validity</th>
      <th>Category</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @producteds.each do |producted| %>
      <tr>
        <td><%= producted.name %></td>
        <td><%= producted.price %></td>
        <td><%= producted.type %></td>
        <td><%= producted.amount %></td>
        <td><%= producted.validity %></td>
        <td><%= producted.category %></td>
      
        <td><%= link_to 'Show', producted %></td>
        <td><%= link_to 'Edit', edit_producted_path(producted) %></td>
        <td><%= link_to 'Destroy', producted, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Producted', new_producted_path %>

app/views/producteds/new.html.erb
<h1>New Producted</h1>

<%= render 'form' %>

<%= link_to 'Back', producteds_path %>

app/views/producteds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @producted.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @producted.price %>
</p>

<p>
  <strong>Type:</strong>
  <%= @producted.type %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @producted.amount %>
</p>

<p>
  <strong>Validity:</strong>
  <%= @producted.validity %>
</p>

<p>
  <strong>Category:</strong>
  <%= @producted.category %>
</p>



<%= link_to 'Edit', edit_producted_path(@producted) %> |
<%= link_to 'Back', producteds_path %>