config/routes.rb
Rails.application.routes.draw do
  resources :products
  get 'base_template/index'
  get 'settings/index'
  get 'settings/custom_account'
  get 'settings/change_password'
  get 'settings/index'
  get 'settings/custom_account'
  get 'stocks/analysis'
  get 'sales/analysis'
  resources :stocks
  resources :producteds
  resources :sales
  resources :companies
  resources :settings
  get 'home/index'
  get 'home/index'
  devise_for :users
  root 'home#index'
end

app/models/sale.rb
class Sale < ActiveRecord::Base
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
   before_action :set_sale, only: [:show, :edit, :update, :destroy]
   
  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
    render layout: "base"
  end
  # GET /sales/1
  # GET /sales/1.json
  def show
  end
  # GEt /sales/analysis
  def analysis
  end
  # GET /sales/new
  def new
    @sale = Sale.new
  end
  # GET /sales/1/edit
  def edit
  end
  # POST /sales
  # POST /sales.json
  def create
      @sale = Sale.new(sale_params)
      respond_to do |format|
      if @sale.save
        format.html {
          redirect_to @sale, notice: 'Sale was successfully created.'
        }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end
  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html {
        redirect_to @sale, notice: 'Sale was successfully updated.'
        }
        format.json {
          render :show, status: :ok, location: @sale
        }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end
  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html {
        redirect_to sales_url, notice: 'Sale was successfully destroyed.'
      }
      format.json {
        head :no_content
      }
      end
    end
    private
     # Use callbacks to share common setup or constraints between actions.
      def set_sale
        @sale = Sale.find(params[:id])
      end
      # Never trust parameters from the scary internet, only allow the white list through.
      def sale_params
        params.require(:sales).permit(:name, :price, :created, :modificated)
      end
    end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= form_for(@sale) do |f| %>
  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% @sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sales/analysis.html.erb
<h1>Teste</h1>

app/views/sales/edit.html.erb
<h1>Editing Sale</h1>

<%= render 'form' %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<p><%= notice %></p>

<h1 class="center">Vendas</h1>






  <%= react_component('SalesAll')%>





  <a data-target="modal" class="btn-floating btn-large  modal-trigger waves-light red right "><i class="material-icons">add</i></a>





<!--<%= link_to 'New Sale', new_sale_path, :class => "btn-floating btn-large waves-effect waves-light right red"  %> -->

app/views/sales/new.html.erb
<h1>New Sale</h1>

<%= render 'form' %>

<%= link_to 'Back', sales_path %>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sale.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @sale.price %>
</p>



<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>